version: '3.8'

services:  

  db:

    container_name: pg_container

    image: postgres

    restart: always

    environment:

      POSTGRES_USER: feliroe

      POSTGRES_PASSWORD: root

      POSTGRES_DB: immoapp

    ports:

      - "1100:1100"

  pgadmin:

    container_name: pgadmin4_container

    image: dpage/pgadmin4

    restart: always

    environment:

      PGADMIN_DEFAULT_EMAIL: feliroe@admin.com

      PGADMIN_DEFAULT_PASSWORD: root

    ports:

      - "1312:80"